### ISSUE TITLE
Format a particular levels and categories different from other levels

### ISSUE THREAD

**Issue by vjpr** [nomiddlename/log4js-node#178]
Basically I want to replicate something like the Rails logger.

Database queries should be formatted in a particular way.

Error messages should be prefixed with their level (ERROR), but the database queries should not be prefixed with their level.

Then all other queries are the same.

Here are my appenders at the moment:

```
    [
      {
        type: 'logLevelFilter'
        level: 'ERROR'
        appender:
          type: 'console'
          layout:
            type: 'pattern'
            pattern: "%[%5p%] #{"%x{filename}".grey} - %m"
            tokens:
              filename: getCallerFile
      }
      {
        type: 'categoryFilter'
        exclude: 'Db'
        appender:
          type: 'console'
          layout:
            type: 'pattern'
            #pattern: "%[%p%] #{"%c".underline} (#{"%x{filename}"}) - %m"
            #pattern: "%[%p%] #{"%c".underline} - %m"
            #pattern: "%[%5p%] #{"%x{filename}".grey} - %m"
            pattern: patterns[5]
            tokens:
              filename: getCallerFile

      }
      {
        type: 'console'
        category: 'connect'
        layout:
          type: 'pattern'
          pattern: "%[%5p%] #{"%m".underline}"
          tokens:
            filename: getCallerFile

      }
      {
        type: 'console'
        category: 'Db'
        layout:
          type: 'pattern'
          pattern: "%m"
      }
    ]
```
